In [2]:
import pandas as pd

In [3]:
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Create a folder in the root directory
!mkdir -p "/content/drive/My Drive/My Folder"

Mounted at /content/drive

In [103]:
#Import datasets
df_news=pd.read_csv('/content/drive/My Drive/My Folder/updated_full_dataset.csv', encoding_errors='ignore')

In [104]:
#Remove rows with NaN
df_news=df_news.dropna(axis=0)
df_news.isnull().sum()

Unnamed: 0.1          0
Unnamed: 0            0
title                 0
content               0
date                  0
Publisher             0
link                  0
Label                 0
day                   0
month                 0
year                  0
content_cleaned       0
content_tokenised     0
content_lowercase     0
content_lemmatised    0
dtype: int64

In [105]:
#Remove unnamed columns
df_news=df_news.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1)

In [106]:
df_news

,title,content,date,Publisher,link,Label,day,month,year,content_cleaned,content_tokenised,content_lowercase,content_lemmatised
0,government must provide security for aml in th...,"Last week, armed men carrying machetes deadly ...",31/07/2023,Gnn News Liberia,https://gnnliberia.com/government-must-provide...,1,31,7,2023,"Last week, armed men carrying machetes deadly ...","['Last', 'week', 'armed', 'men', 'carrying', '...","['last', 'week', 'armed', 'men', 'carrying', '...",last week armed men carrying machete deadly we...
1,liberia army chief of staff predicts unforesee...,"Amid recent coup Niger, Chief Staff Liberian a...",28/07/2023,Gnn News Liberia,https://gnnliberia.com/liberia-army-chief-of-s...,1,28,7,2023,"Amid recent coup Niger, Chief Staff Liberian a...","['Amid', 'recent', 'coup', 'Niger', 'Chief', '...","['amid', 'recent', 'coup', 'niger', 'chief', '...",amid recent coup niger chief staff liberian ar...
2,guns machetes men attack vandalize arcelormit...,"A group unknown men said Zolowee, town proximi...",30/07/2023,Gnn News Liberia,https://gnnliberia.com/guns-machetes-men-attac...,1,30,7,2023,"A group unknown men said Zolowee, town proximi...","['group', 'unknown', 'men', 'said', 'Zolowee',...","['group', 'unknown', 'men', 'said', 'zolowee',...",group unknown men said zolowee town proximity ...
3,president Â weah commits to delivering violent...,"Liberian President, George Weah, pledged deliv...",27/07/2023,Gnn News Liberia,https://gnnliberia.com/president-weah-commits-...,1,27,7,2023,"Liberian President, George Weah, pledged deliv...","['Liberian', 'President', 'George', 'Weah', 'p...","['liberian', 'president', 'george', 'weah', 'p...",liberian president george weah pledged deliver...
4,new world bank liberia country manager arrives,"MONROVIA, July 31, 2023 Ã¢â¬?The new World Ba...",31/07/2023,Gnn News Liberia,https://gnnliberia.com/new-world-bank-liberia-...,1,31,7,2023,"MONROVIA, July , ?The new World Bank Country ...","['MONROVIA', 'July', 'new', 'World', 'Bank', '...","['monrovia', 'july', 'new', 'world', 'bank', '...",monrovia july new world bank country manager l...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31485,the world bank did not praise tanzanias antico...,Articles claiming World Bank applauded Tanzani...,21/04/2020 18:24,Afp Fact check,https://factcheck.afp.com/world-bank-did-not-p...,0,21,4,2020,Articles claiming World Bank applauded Tanzani...,"['Articles', 'claiming', 'World', 'Bank', 'app...","['articles', 'claiming', 'world', 'bank', 'app...",article claiming world bank applauded tanzania...
31486,tv report shows an unrelated guinea incident p...,A YouTube video shared thousands times claims ...,15/05/2020 15:11,Afp Fact check,https://factcheck.afp.com/tv-report-shows-unre...,0,15,5,2020,A YouTube video shared thousands times claims ...,"['YouTube', 'video', 'shared', 'thousands', 't...","['youtube', 'video', 'shared', 'thousands', 't...",youtube video shared thousand time claim two c...
31487,this video shows a flypast rehearsal for south...,A video shared thousands times Facebook purpor...,04/05/2020 18:04,Afp Fact check,https://factcheck.afp.com/video-shows-flypast-...,0,4,5,2020,A video shared thousands times Facebook purpor...,"['video', 'shared', 'thousands', 'times', 'Fac...","['video', 'shared', 'thousands', 'times', 'fac...",video shared thousand time facebook purport sh...
31488,african mistrust of western vaccines threatens...,The race find vaccine novel coronavirus faces ...,05/05/2020 17:02,Afp Fact check,https://factcheck.afp.com/african-mistrust-wes...,0,5,5,2020,The race find vaccine novel coronavirus faces ...,"['race', 'find', 'vaccine', 'novel', 'coronavi...","['race', 'find', 'vaccine', 'novel', 'coronavi...",race find vaccine novel coronavirus face uphil...
31489,EFF party leader did not file lawsuit to shut ...,A post shared hundreds of times on Facebook i...,16/06/2021 14:41,Afp Fact check,https://factcheck.afp.com/eff-party-leader-did...,0,16,6,2021,A post shared hundreds of times on Facebook in...,"['post', 'shared', 'hundreds', 'times', 'Faceb...","['post', 'shared', 'hundreds', 'times', 'faceb...",post shared hundred time facebook south africa...

EDA

In [5]:
import plotly.express as px
import plotly.graph_objects as go
import nltk
nltk.download('averaged_perceptron_tagger')
from collections import Counter

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [108]:
df_news.dtypes

title                 object
content               object
date                  object
Publisher             object
link                  object
Label                  int64
day                    int64
month                  int64
year                   int64
content_cleaned       object
content_tokenised     object
content_lowercase     object
content_lemmatised    object
dtype: object

News Collection Count by Years

In [109]:
#Visualise the news count by year
date_count=df_news['year'].value_counts()
fig=px.histogram(df_news, x='year', title='News Count by Year', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(title='Publication Year').update_yaxes(title='News Count')
fig.update_layout(width=1000, height=500, bargap=0.03)
fig.show()

Distribution of fake and real news

In [110]:
#Ratio of fake and real news
r_real=round((df_news['Label'].value_counts()[1])/len(df_news), 3)
r_fake=round((df_news['Label'].value_counts()[0])/len(df_news), 3)
print('The ratio of fake and real news: \n')
print('Real news:{}\nFake news:{}'.format(r_real, r_fake))

The ratio of fake and real news:

Real news:0.828
Fake news:0.172

In [111]:
#Visualise the number of fake and real news
#label_count=df_news['Label (Fake-0| True-1)'].value_counts()
fig=px.histogram(df_news, x='Label', title='Distribution of fake and factual news', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(type='category', title='News Label').update_yaxes(title='News Count')
fig.update_layout(width=1000, height=500, bargap=0.03)
fig.show()

Text Length

In [112]:
#Visualise news lenght count
df_news['content_length']=''
for index, r in df_news.iterrows():
  df_news.at[index,'content_length']=len(r['content_cleaned'])

fig=px.histogram(df_news, x='content_length', title='News Text Length Count', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
fig.update_xaxes(title='Text length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

Average Word Length

In [113]:
#calculation
df_news['aver_word_length']=''
for index, r in df_news.iterrows():
  words=r['content_cleaned'].split()
  df_news.at[index,'aver_word_length']=sum(len(word) for word in words)/len(words)

In [114]:
#visualisation
fig=px.histogram(df_news, x='aver_word_length', title='Average Word Length Count', barmode='overlay', color='Label', color_discrete_sequence=["#676FA3", "#FF5959"])
#fig.update_xaxes(title='Average Word length').update_yaxes(title='News Count')
fig.update_layout(width=1400, height=500)
fig.show()

In [15]:
#Save to csv
df_news.to_csv("/content/drive/My Drive/My Folder/detailed_full_dataset.csv")

POS Tag Counts

In [115]:
def get_post_tags_list(tokenised_text):
  all_pos_tags=[]
  for word in tokenised_text:
    pos_tag=nltk.pos_tag([word])[0][1]
    all_pos_tags.append(pos_tag)
  return all_pos_tags

In [117]:
df_news.loc[23223]['content_tokenised']

"['MONROVIA', 'Montserrado', 'Liberia', 'National', 'Police', 'says', 'received', 'information', 'linking', 'Monrovias', 'Mayor', 'Jefferson', 'Koijee', 'electoral', 'violence', 'reported', 'Saturday', 'Montserrados', 'district', 'Saturday', 'Cornelia', 'KruahTogba', 'running', 'Unity', 'Party', 'ticket', 'supported', 'Alternative', 'National', 'Congress', 'Liberty', 'Party', 'reported', 'live', 'video', 'campaign', 'rally', 'violently', 'interrupted', 'members', 'Coalition', 'Democratic', 'Change', 'led', 'Koijee', 'several', 'supporters', 'physically', 'wounded', 'KruahTogba', 'said', 'alerted', 'one', 'supporters', 'stabbed', 'death', 'noted', 'found', 'young', 'lady', 'Liberty', 'Party', 'political', 'leader', 'Grand', 'Bassa', 'senator', 'Nyonblee', 'KarngaLawrence', 'rally', 'directly', 'accused', 'mayor', 'involved', 'act', 'reports', 'social', 'media', 'mayor', 'men', 'possession', 'gun', 'cutlasses', 'Eyewitnesses', 'said', 'mayor', 'seen', 'walking', 'individuals', 'dressed', 'militarylike', 'outfits', 'holding', 'cutlasses', 'said', 'heard', 'two', 'gunshots', 'violence', 'Saturday', 'However', 'police', 'spokesman', 'Moses', 'Carter', 'told', 'Bush', 'Chicken', 'claims', 'Koijee', 'involved', 'violence', 'mere', 'allegationsThe', 'police', 'earlier', 'denied', 'reports', 'death', 'occurred', 'result', 'Saturdays', 'violence', 'Carter', 'challenged', 'making', 'accusations', 'produce', 'information', 'proved', 'mayor', 'involved', 'Spokesman', 'Liberia', 'National', 'Police', 'Moses', 'Carter', 'Photo', 'Gbatemah', 'Senah', 'said', 'four', 'individuals', 'wounded', 'including', 'female', 'supporter', 'Unity', 'Partys', 'candidate', 'three', 'male', 'supporters', 'candidate', 'contesting', 'ticket', 'Coalition', 'Democratic', 'Change', 'John', 'Weah', 'police', 'spokesman', 'said', 'determination', 'weapons', 'used', 'caused', 'injuries', 'four', 'individuals', 'said', 'police', 'establish', 'responsible', 'violence', 'KruahTogba', 'refuted', 'Carters', 'statements', 'adding', 'several', 'supporters', 'wounded', 'said', 'victims', 'reportedly', 'refused', 'local', 'clinics', 'due', 'lack', 'space', 'team', 'still', 'searching', 'victims', 'provide', 'assistance', 'police', 'biased', 'government', 'dont', 'expect', 'anything', 'lesssaid', 'noting', 'police', 'pickup', 'helped', 'take', 'several', 'wounded', 'people', 'medical', 'facilities', 'told', 'Bush', 'Chicken', 'personally', 'saw', 'Koijee', 'along', 'men', 'dressed', 'black', 'red', 'berets', 'participate', 'violence', 'said', 'team', 'identified', 'victims', 'local', 'clinics', 'paid', 'medical', 'bills', 'maintained', 'earlier', 'statement', 'female', 'supporter', 'reportedly', 'stabbed', 'death', 'team', 'working', 'identify', 'hospital', 'taken', 'trying', 'trace', 'identity', 'family', 'According', 'KruahTogba', 'driver', 'pickup', 'victim', 'rode', 'prior', 'violence', 'suggested', 'victim', 'probably', 'resident', 'Barnesville', 'community', 'Meanwhile', 'said', 'one', 'team', 'members', 'received', 'call', 'mans', 'sister', 'stabbed', 'team', 'working', 'locate', 'probable', 'relative', 'victim', 'KruahTogba', 'said', 'violent', 'incident', 'led', 'damage', 'properties', 'including', 'church', 'campaign', 'billboard', 'truck', 'using', 'political', 'rally', 'well', 'public', 'address', 'system', 'windshield', 'taxi', 'completely', 'broken', 'CDC', 'partisans', 'Pictures', 'damage', 'properties', 'posted', 'Facebook', 'time', 'accused', 'police', 'firing', 'tear', 'gas', 'supporters', 'damaging', 'windows', 'home', 'firing', 'tear', 'gas', 'suffocated', 'home', 'nurse', 'little', 'kid', 'indoors', 'head', 'Unity', 'Partys', 'Mobilization', 'Committee', 'Montserrados', 'district', 'Alexander', 'Harris', 'confirmed', 'police', 'officers', 'board', 'pickup', 'marked', 'GSALNP', 'license', 'plate', 'number', 'RL', 'fired', 'tear', 'gas', 'supporters', 'home', 'KruahTogba', 'According', 'Harris', 'another', 'police', 'pickup', 'marked', 'RL', 'transported', 'several', 'injured', 'supporters', 'unknown', 'destinations', 'said', 'man', 'identified', '\\x8bWidell', 'commander', 'board', 'pickup', 'took', 'away', 'wounded', 'supporters', 'disclosed', 'Unity', 'Partys', 'candidate', 'team', 'paid', 'bill', 'L', 'US', 'balance', 'L', 'US', 'six', 'supporters', 'injured', 'violence', 'said', 'another', 'guy', 'stabbed', 'neck', 'admitted', 'Kamaras', 'Clinic', 'Iron', 'Factory', 'asked', 'police', 'spokesman', 'Carter', 'said', 'confirm', 'claims', 'officers', 'firing', 'tear', 'gas', 'noted', 'tear', 'gas', 'fired', 'harm', 'anyone', 'rather', 'dislodge', 'people', 'violent', 'incidents']"

In [100]:
remove_ac(df_news.loc[23223]['content_tokenised'])

"['MONROVIA', 'Montserrado', '\\x9a', 'Liberia', 'National', 'Police', 'says', 'received', 'information', 'linking', 'Monrovia\\x9a\\x9es', 'Mayor', 'Jefferson', 'Koijee', 'electoral', 'violence', 'reported', 'Saturday', 'Montserrado\\x9a\\x9es', 'district', 'Saturday', 'Cornelia', 'KruahTogba', 'running', 'Unity', 'Party', 'ticket', 'supported', 'Alternative', 'National', 'Congress', 'Liberty', 'Party', 'reported', 'live', 'video', 'campaign', 'rally', 'violently', 'interrupted', 'members', 'Coalition', 'Democratic', 'Change', 'led', 'Koijee', 'several', 'supporters', 'physically', 'wounded', 'KruahTogba', 'said', 'alerted', 'one', 'supporters', 'stabbed', 'death', 'noted', 'found', 'young', 'lady', 'Liberty', 'Party', 'political', 'leader', 'Grand', 'Bassa', 'senator', 'Nyonblee', 'KarngaLawrence', 'rally', 'directly', 'accused', 'mayor', 'involved', 'act', 'reports', 'social', 'media', 'mayor', 'men', 'possession', 'gun', 'cutlasses', 'Eyewitnesses', 'said', 'mayor', 'seen', 'walking', 'individuals', 'dressed', 'militarylike', 'outfits', 'holding', 'cutlasses', 'said', 'heard', 'two', 'gunshots', 'violence', 'Saturday', 'However', 'police', 'spokesman', 'Moses', 'Carter', 'told', 'Bush', 'Chicken', 'claims', 'Koijee', 'involved', 'violence', '\\x9a', 'mere', 'allegations\\x9aThe', 'police', 'earlier', 'denied', 'reports', 'death', 'occurred', 'result', 'Saturday\\x9a\\x9es', 'violence', 'Carter', 'challenged', 'making', 'accusations', 'produce', 'information', 'proved', 'mayor', 'involved', 'Spokesman', 'Liberia', 'National', 'Police', 'Moses', 'Carter', 'Photo', 'Gbatemah', 'Senah', 'said', 'four', 'individuals', 'wounded', 'including', 'female', 'supporter', 'Unity', 'Party\\x9a\\x9es', 'candidate', 'three', 'male', 'supporters', 'candidate', 'contesting', 'ticket', 'Coalition', 'Democratic', 'Change', 'John', 'Weah', 'police', 'spokesman', 'said', 'determination', 'weapons', 'used', 'caused', 'injuries', 'four', 'individuals', 'said', 'police', 'establish', 'responsible', 'violence', 'KruahTogba', 'refuted', 'Carter\\x9a\\x9es', 'statements', 'adding', 'several', 'supporters', 'wounded', '\\x9aShe', 'said', 'victims', 'reportedly', 'refused', 'local', 'clinics', 'due', 'lack', 'space', 'team', 'still', 'searching', 'victims', 'provide', 'assistance', '\\x9a', 'police', 'biased', 'It\\x9a\\x9es', 'government', 'don\\x9a\\x9et', 'expect', 'anything', 'less\\x9asaid', 'noting', 'police', 'pickup', 'helped', 'take', 'several', 'wounded', 'people', 'medical', 'facilities', 'told', 'Bush', 'Chicken', 'personally', 'saw', 'Koijee', 'along', 'men', 'dressed', 'black', 'red', 'berets', 'participate', 'violence', 'said', 'team', 'identified', 'victims', 'local', 'clinics', 'paid', 'medical', 'bills', 'maintained', 'earlier', 'statement', 'female', 'supporter', 'reportedly', 'stabbed', 'death', 'team', 'working', 'identify', 'hospital', 'taken', 'trying', 'trace', 'identity', 'family', 'According', 'KruahTogba', 'driver', 'pickup', 'victim', 'rode', 'prior', 'violence', 'suggested', 'victim', 'probably', 'resident', 'Barnesville', 'community', 'Meanwhile', 'said', 'one', 'team', 'members', 'received', 'call', 'man\\x9a\\x9es', 'sister', 'stabbed', 'team', 'working', 'locate', 'probable', 'relative', 'victim', 'KruahTogba', 'said', 'violent', 'incident', 'led', 'damage', 'properties', 'including', 'church', 'campaign', 'billboard', 'truck', 'using', 'political', 'rally', 'well', 'public', 'address', 'system', 'windshield', 'taxi', 'completely', 'broken', 'CDC', 'partisans', 'Pictures', 'damage', 'properties', 'posted', 'Facebook', 'time', 'accused', 'police', 'firing', 'tear', 'gas', 'supporters', 'damaging', 'windows', 'home', 'firing', 'tear', 'gas', 'suffocated', 'home', 'nurse', 'little', 'kid', 'indoors', 'head', 'Unity', 'Party\\x9a\\x9es', 'Mobilization', 'Committee', 'Montserrado\\x9a\\x9es', 'district', 'Alexander', 'Harris', 'confirmed', 'police', 'officers', 'board', 'pickup', 'marked', 'GSALNP', 'license', 'plate', 'number', 'RL', 'fired', 'tear', 'gas', 'supporters', 'home', 'KruahTogba', 'According', 'Harris', 'another', 'police', 'pickup', 'marked', 'RL', 'transported', 'several', 'injured', 'supporters', 'unknown', 'destinations', 'said', 'man', 'identified', '\\x9a\\x8bWidell\\x9a\\x9e', 'commander', 'board', 'pickup', 'took', 'away', 'wounded', 'supporters', 'disclosed', 'Unity', 'Party\\x9a\\x9es', 'candidate', 'team', 'paid', 'bill', 'L', 'US', 'balance', 'L', 'US', 'six', 'supporters', 'injured', 'violence', 'said', 'another', 'guy', 'stabbed', 'neck', 'admitted', 'Kamara\\x9a\\x9es', 'Clinic', 'Iron', 'Factory', 'asked', 'police', 'spokesman', 'Carter', 'said', 'confirm', 'claims', 'officers', 'firing', 'tear', 'gas', 'noted', 'tear', 'gas', 'fired', 'harm', 'anyone', 'rather', 'dislodge', 'people', 'violent', 'incidents']"

In [118]:
#update tokenised content
for index, r in df_news.iterrows():
  t1=r['content_tokenised'].replace("['", "")
  t1=t1.replace("']", "")
  t1=t1.split("', '")
  df_news.at[index,'content_tokenised']=t1

df_news

,title,content,date,Publisher,link,Label,day,month,year,content_cleaned,content_tokenised,content_lowercase,content_lemmatised,content_length,aver_word_length
0,government must provide security for aml in th...,"Last week, armed men carrying machetes deadly ...",31/07/2023,Gnn News Liberia,https://gnnliberia.com/government-must-provide...,1,31,7,2023,"Last week, armed men carrying machetes deadly ...","[Last, week, armed, men, carrying, machetes, d...","['last', 'week', 'armed', 'men', 'carrying', '...",last week armed men carrying machete deadly we...,2412,6.859935
1,liberia army chief of staff predicts unforesee...,"Amid recent coup Niger, Chief Staff Liberian a...",28/07/2023,Gnn News Liberia,https://gnnliberia.com/liberia-army-chief-of-s...,1,28,7,2023,"Amid recent coup Niger, Chief Staff Liberian a...","[Amid, recent, coup, Niger, Chief, Staff, Libe...","['amid', 'recent', 'coup', 'niger', 'chief', '...",amid recent coup niger chief staff liberian ar...,2232,6.617747
2,guns machetes men attack vandalize arcelormit...,"A group unknown men said Zolowee, town proximi...",30/07/2023,Gnn News Liberia,https://gnnliberia.com/guns-machetes-men-attac...,1,30,7,2023,"A group unknown men said Zolowee, town proximi...","[group, unknown, men, said, Zolowee, town, pro...","['group', 'unknown', 'men', 'said', 'zolowee',...",group unknown men said zolowee town proximity ...,2018,6.522388
3,president Â weah commits to delivering violent...,"Liberian President, George Weah, pledged deliv...",27/07/2023,Gnn News Liberia,https://gnnliberia.com/president-weah-commits-...,1,27,7,2023,"Liberian President, George Weah, pledged deliv...","[Liberian, President, George, Weah, pledged, d...","['liberian', 'president', 'george', 'weah', 'p...",liberian president george weah pledged deliver...,2342,7.04811
4,new world bank liberia country manager arrives,"MONROVIA, July 31, 2023 Ã¢â¬?The new World Ba...",31/07/2023,Gnn News Liberia,https://gnnliberia.com/new-world-bank-liberia-...,1,31,7,2023,"MONROVIA, July , ?The new World Bank Country ...","[MONROVIA, July, new, World, Bank, Country, Ma...","['monrovia', 'july', 'new', 'world', 'bank', '...",monrovia july new world bank country manager l...,1217,7.05298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31485,the world bank did not praise tanzanias antico...,Articles claiming World Bank applauded Tanzani...,21/04/2020 18:24,Afp Fact check,https://factcheck.afp.com/world-bank-did-not-p...,0,21,4,2020,Articles claiming World Bank applauded Tanzani...,"[Articles, claiming, World, Bank, applauded, T...","['articles', 'claiming', 'world', 'bank', 'app...",article claiming world bank applauded tanzania...,3335,6.805621
31486,tv report shows an unrelated guinea incident p...,A YouTube video shared thousands times claims ...,15/05/2020 15:11,Afp Fact check,https://factcheck.afp.com/tv-report-shows-unre...,0,15,5,2020,A YouTube video shared thousands times claims ...,"[YouTube, video, shared, thousands, times, cla...","['youtube', 'video', 'shared', 'thousands', 't...",youtube video shared thousand time claim two c...,3727,6.296078
31487,this video shows a flypast rehearsal for south...,A video shared thousands times Facebook purpor...,04/05/2020 18:04,Afp Fact check,https://factcheck.afp.com/video-shows-flypast-...,0,4,5,2020,A video shared thousands times Facebook purpor...,"[video, shared, thousands, times, Facebook, pu...","['video', 'shared', 'thousands', 'times', 'fac...",video shared thousand time facebook purport sh...,1366,6.423913
31488,african mistrust of western vaccines threatens...,The race find vaccine novel coronavirus faces ...,05/05/2020 17:02,Afp Fact check,https://factcheck.afp.com/african-mistrust-wes...,0,5,5,2020,The race find vaccine novel coronavirus faces ...,"[race, find, vaccine, novel, coronavirus, face...","['race', 'find', 'vaccine', 'novel', 'coronavi...",race find vaccine novel coronavirus face uphil...,6904,6.691193
31489,EFF party leader did not file lawsuit to shut ...,A post shared hundreds of times on Facebook i...,16/06/2021 14:41,Afp Fact check,https://factcheck.afp.com/eff-party-leader-did...,0,16,6,2021,A post shared hundreds of times on Facebook in...,"[post, shared, hundreds, times, Facebook, Sout...","['post', 'shared', 'hundreds', 'times', 'faceb...",post shared hundred time facebook south africa...,2337,4.81

In [64]:
df_news.loc[31460]['content_tokenised']

['Numerous',
 'claims',
 'widely',
 'shared',
 'social',
 'media',
 'allege',
 'actordirector',
 'Mel',
 'Gibson',
 'accused',
 'Hollywood',
 'involved',
 'ritualistic',
 'child',
 'sacrifices',
 'paedophilia',
 'However',
 'AFP',
 'Fact',
 'Check',
 'found',
 'public',
 'record',
 'quotes',
 'attributed',
 'publicist',
 'dismissed',
 'claims',
 'false',
 'Facebook',
 'post',
 'shared',
 'nearly',
 'times',
 'South',
 'Africa',
 'claims',
 'Mel',
 'Gibson',
 'blown',
 'whistle',
 'epidemic',
 'Ëparasites',
 'Ëcontrol',
 'Hollywood',
 'involved',
 'childSacrifice',
 'pedophiliasic',
 'screenshot',
 'taken',
 'July',
 'misleading',
 'Facebook',
 'post',
 'post',
 'alleges',
 'star',
 'said',
 'every',
 'studio',
 'Hollywood',
 'bought',
 'paid',
 'blood',
 'innocent',
 'children',
 'Internet',
 'searches',
 'posts',
 'headline',
 'MEL',
 'GIBSONS',
 'SHOCKING',
 'REVELATION',
 'HOLLYWOODfound',
 'articles',
 'content',
 'March',
 'claim',
 'quotes',
 'Gibson',
 'saying',
 'key',
 'players',
 'movie',
 'business',
 'perform',
 'sacred',
 'rituals',
 'sick',
 'totally',
 'odds',
 'moral',
 'fabric',
 'binds',
 'patriotic',
 'Americans',
 'worst',
 'part',
 'open',
 'secret',
 'Hollywood',
 'everyone',
 'wants',
 'itIt',
 'alleges',
 'actor',
 'made',
 'comments',
 'promoting',
 'movie',
 'Daddys',
 'Home',
 'London',
 'specifically',
 'post',
 'claims',
 'Gibson',
 'said',
 'things',
 'TV',
 'guests',
 'backstage',
 'appearing',
 'Graham',
 'Norton',
 'Show',
 'Brief',
 'red',
 'carpet',
 'interviews',
 'London',
 'premiere',
 'strictly',
 'promoted',
 'comedy',
 'nothing',
 'else',
 'said',
 'another',
 'interview',
 'Gibson',
 'fellow',
 'actor',
 'John',
 'Lithgow',
 'taught',
 'dad',
 'jokes',
 'closest',
 'Gibson',
 'appears',
 'speak',
 'entertainment',
 'industry',
 'movies',
 'promotion',
 'interview',
 'alongside',
 'Lithgow',
 'pair',
 'asked',
 'Associated',
 'Press',
 'Weinstein',
 'sexual',
 'harassment',
 'scandal',
 'Gibson',
 'describes',
 'tragic',
 'healing',
 'processmakes',
 'none',
 'utterances',
 'claimed',
 'fake',
 'posts',
 'Part',
 'claim',
 'Gibson',
 'made',
 'comments',
 'appearing',
 'Graham',
 'Norton',
 'Show',
 'British',
 'television',
 'allegedly',
 'called',
 'Hollywood',
 'institutionalised',
 'pedophile',
 'ringuse',
 'abuse',
 'kids',
 'sick',
 'spiritual',
 'beliefsHe',
 'purported',
 'said',
 'blacklisted',
 'Hollywood',
 'voicing',
 'opinions',
 'industry',
 'clashed',
 'liberal',
 'agendaGibson',
 'featured',
 'least',
 'movies',
 'see',
 'blood',
 'sexually',
 'abused',
 'infant',
 'Ëultimate',
 'prize',
 'say',
 'Ëhighly',
 'enriched',
 'Babies',
 'Ëpremium',
 'currency',
 'hold',
 'higher',
 'value',
 'anything',
 'think',
 'Diamonds',
 'drugs',
 'caviar',
 'name',
 'literally',
 'trading',
 'kids',
 'currency',
 'favors',
 'movie',
 'roles',
 'kickbackclaims',
 'go',
 'say',
 'record',
 'public',
 'record',
 'anywhere',
 'Gibson',
 'making',
 'statements',
 'publicist',
 'Alan',
 'Nierob',
 'denied',
 'actor',
 'said',
 'quotes',
 'attributed',
 'Nierob',
 'told',
 'AFP',
 'Fact',
 'Check',
 'seen',
 'claims',
 'know',
 'stem',
 'AFP',
 'Fact',
 'Check',
 'traced',
 'probable',
 'origin',
 'claims',
 'story',
 'published',
 'website',
 'formerly',
 'called',
 'News',
 'Wire',
 'changed',
 'name',
 'removed',
 'online',
 'article',
 'failing',
 'meet',
 'editorial',
 'standards',
 'moved',
 'domains',
 'NewsPunchcom',
 'stories',
 'longer',
 'adhered',
 'new',
 'editorial',
 'standardsWe',
 'originally',
 'published',
 'story',
 'old',
 'domain',
 'YourNewsWirecom',
 'back',
 'said',
 'Sean',
 'AdlTabatabai',
 'cofounder',
 'News',
 'Punch',
 'formerly',
 'News',
 'Wire',
 'email',
 'AFP',
 'Fact',
 'Check',
 'Back',
 'screen',
 'bizarre',
 'stories',
 'people',
 'emailed',
 'source',
 'stories',
 'obscure',
 'blogs',
 'web',
 'many',
 'stories',
 'published',
 'websiteThe',
 'author',
 'submitted',
 'content',
 'subsequently',
 'promoted',
 'link',
 'Facebook',
 'page',
 'Baxter',
 'Dmitry',
 'Facebook',
 'page',
 'describes',
 'journalist',
 'passionate',
 'motor',
 'sports',
 'military',
 'history',
 'truth',
 'moved',
 'domains',
 'NewsPunchcom',
 'stories',
 'longer',
 'adhered',
 'new',
 'editorial',
 'standardsAdlTabatabai',
 'said',
 'Specifically',
 'proof',
 'Mel',
 'Gibson',
 'said',
 'statements',
 'quoted',
 'original',
 'article',
 'decided',
 'unpublish',
 'story',
 'claims',
 'made',
 'adequately',
 'factchecked',
 'usStill',
 'hasnt',
 'stopped',
 'claim',
 'spreading',
 'online',
 'particularly',
 'among',
 'QAnon',
 'conspiracy',
 'communities',
 'Facebook',
 'page',
 'called',
 'Chasing',
 'White',
 'Rabbit',
 'anon',
 'v',
 'Revived',
 'shared',
 'post',
 'page',
 'previously',
 'shut',
 'recreated',
 'January',
 'managed',
 'three',
 'people',
 'Poland',
 'one',
 'person',
 'United',
 'States',
 'according',
 'Facebook',
 'page',
 'transparency',
 'information',
 'promotes',
 'idea',
 'deep',
 'state',
 'satanic',
 'mafia',
 'rules',
 'every',
 'aspect',
 'world',
 'QAnon',
 'adherents',
 'generally',
 'believe',
 'dozens',
 'global',
 'elites',
 'many',
 'seen',
 'left',
 'wingliberal',
 'behind',
 'worldwide',
 'paedophile',
 'network',
 'Part',
 'narrative',
 'casts',
 'US',
 'President',
 'Donald',
 'Trump',
 'avenger',
 'abused',
 'children',
 'saviour',
 'humanity',
 'Another',
 'recent',
 'post',
 'published',
 'page',
 'factchecked',
 'independent',
 'organisations',
 'Gibson',
 'took',
 'flak',
 'antiSemitic',
 'tirade',
 'drunkdriving',
 'arrest',
 'later',
 'apologised',
 'blaming',
 'alcoholism',
 'voiced',
 'criticism',
 'Hollywood',
 'past',
 'clip',
 'old',
 'interview',
 'shared',
 'YouTube',
 'Gibson',
 'spoke',
 'arriving',
 'Hollywood',
 'cockroach',
 'resilienceperson',
 'needs',
 'survive',
 'town',
 'edited',
 'clip',
 'easily',
 'taken',
 'context',
 'Gibson',
 'says',
 'place',
 'humiliate',
 'humbling',
 'rip',
 'life',
 'pieces',
 'youll',
 'let',
 'always',
 'pounding',
 'walls',
 'little',
 'guys',
 'little',
 'heathens',
 'soul',
 'downstairs',
 'horns',
 'heads',
 'battering',
 'ram',
 'trying',
 'beat',
 'walls',
 'thats',
 'devils',
 'knowHowever',
 'doesnt',
 'say',
 'anything',
 'paedophilia',
 'child',
 'sacrifices']

In [46]:
for w in df_news.loc[0]['content_lemmatised'].split(" "):
  print(nltk.pos_tag([w]))

[('last', 'JJ')]
[('week', 'NN')]
[('armed', 'VBN')]
[('men', 'NNS')]
[('carrying', 'VBG')]
[('machete', 'NN')]
[('deadly', 'RB')]
[('weapon', 'NN')]
[('attacked', 'VBN')]
[('arcelormittals', 'NNS')]
[('tokadeh', 'NN')]
[('mine', 'NN')]
[('yekepa', 'NN')]
[('shot', 'NN')]
[('employee', 'NN')]
[('violent', 'NN')]
[('attack', 'NN')]
[('masterminded', 'VBN')]
[('gang', 'NN')]
[('criminal', 'JJ')]
[('said', 'VBD')]
[('stationed', 'VBN')]
[('town', 'NN')]
[('zolowee', 'NN')]
[('within', 'IN')]
[('confines', 'NNS')]
[('arcelormittals', 'NNS')]
[('operational', 'JJ')]
[('area', 'NN')]
[('nimba', 'NN')]
[('county', 'NN')]
[('criminal', 'JJ')]
[('earlier', 'RBR')]
[('opened', 'VBN')]
[('fire', 'NN')]
[('police', 'NNS')]
[('officer', 'NN')]
[('town', 'NN')]
[('officer', 'NN')]
[('discovered', 'VBN')]
[('warehouse', 'NN')]
[('stolen', 'VBN')]
[('fuel', 'NN')]
[('oil', 'NN')]
[('yellow', 'NN')]
[('machine', 'NN')]
[('spare', 'NN')]
[('part', 'NN')]
[('flogged', 'VBN')]
[('segal', 'NN')]
[('private', 'JJ')]
[('security', 'NN')]
[('guard', 'NN')]
[('duty', 'NN')]
[('damaged', 'VBN')]
[('vehicle', 'NN')]
[('attack', 'NN')]
[('tokadeh', 'NN')]
[('mine', 'NN')]
[('arcelormittal', 'NN')]
[('liberia', 'NN')]
[('aml', 'NN')]
[('confirmed', 'VBN')]
[('situation', 'NN')]
[('continue', 'NN')]
[('work', 'NN')]
[('ensure', 'VB')]
[('safety', 'NN')]
[('wellbeing', 'VBG')]
[('emplyoees', 'NNS')]
[('remain', 'NN')]
[('top', 'NN')]
[('priority', 'NN')]
[('since', 'IN')]
[('volent', 'NN')]
[('gang', 'NN')]
[('attack', 'NN')]
[('mounting', 'VBG')]
[('fear', 'NN')]
[('uncertainty', 'NN')]
[('engulfed', 'NN')]
[('community', 'NN')]
[('around', 'IN')]
[('arcelormittals', 'NNS')]
[('mining', 'NN')]
[('site', 'NN')]
[('nimba', 'NN')]
[('county', 'NN')]
[('people', 'NNS')]
[('zolowee', 'NN')]
[('town', 'NN')]
[('gang', 'NN')]
[('opened', 'VBN')]
[('gun', 'NN')]
[('fire', 'NN')]
[('police', 'NNS')]
[('officer', 'NN')]
[('beat', 'NN')]
[('private', 'JJ')]
[('security', 'NN')]
[('guard', 'NN')]
[('even', 'RB')]
[('terrified', 'VBN')]
[('given', 'VBN')]
[('shock', 'NN')]
[('last', 'JJ')]
[('week', 'NN')]
[('event', 'NN')]
[('disturbing', 'VBG')]
[('fact', 'NN')]
[('first', 'RB')]
[('kind', 'NN')]
[('company', 'NN')]
[('come', 'VB')]
[('repeated', 'VBN')]
[('attack', 'NN')]
[('criminal', 'JJ')]
[('gang', 'NN')]
[('government', 'NN')]
[('liberia', 'NN')]
[('step', 'NN')]
[('immediately', 'RB')]
[('provide', 'NN')]
[('security', 'NN')]
[('biggest', 'JJS')]
[('foreign', 'JJ')]
[('direct', 'JJ')]
[('investment', 'NN')]
[('country', 'NN')]
[('ensure', 'VB')]
[('safety', 'NN')]
[('company', 'NN')]
[('employee', 'NN')]
[('well', 'RB')]
[('company', 'NN')]
[('property', 'NN')]
[('acelormittal', 'NN')]
[('several', 'JJ')]
[('year', 'NN')]
[('biggest', 'JJS')]
[('taxpayer', 'NN')]
[('government', 'NN')]
[('apart', 'RB')]
[('mda', 'NN')]
[('responsibility', 'NN')]
[('demonstrated', 'VBN')]
[('ample', 'NN')]
[('commitment', 'NN')]
[('patriotism', 'NN')]
[('country', 'NN')]
[('providing', 'VBG')]
[('support', 'NN')]
[('critical', 'JJ')]
[('area', 'NN')]
[('health', 'NN')]
[('education', 'NN')]
[('infrastructure', 'NN')]
[('sport', 'NN')]
[('etc', 'NN')]
[('last', 'JJ')]
[('two', 'CD')]
[('year', 'NN')]
[('liberia', 'NN')]
[('revenue', 'NN')]
[('authority', 'NN')]
[('awarded', 'VBN')]
[('aml', 'NN')]
[('country', 'NN')]
[('biggest', 'JJS')]
[('taxpayer', 'NN')]
[('tax', 'NN')]
[('compliant', 'NN')]
[('recent', 'JJ')]
[('attack', 'NN')]
[('company', 'NN')]
[('mining', 'NN')]
[('site', 'NN')]
[('nimba', 'NN')]
[('instilling', 'VBG')]
[('wonton', 'NN')]
[('fear', 'NN')]
[('among', 'IN')]
[('several', 'JJ')]
[('employee', 'NN')]
[('resident', 'NN')]
[('nearby', 'RB')]
[('community', 'NN')]
[('speculated', 'VBN')]
[('incident', 'NN')]
[('took', 'VBD')]
[('place', 'NN')]
[('company', 'NN')]
[('employee', 'NN')]
[('assigned', 'VBN')]
[('tokodehs', 'NN')]
[('mining', 'NN')]
[('site', 'NN')]
[('nimba', 'NN')]
[('county', 'NN')]
[('reluctantly', 'RB')]
[('showing', 'VBG')]
[('job', 'NN')]
[('due', 'JJ')]
[('fear', 'NN')]
[('criminal', 'JJ')]
[('may', 'MD')]
[('return', 'NN')]
[('harm', 'NN')]
[('life', 'NN')]
[('security', 'NN')]
[('officer', 'NN')]
[('assigned', 'VBN')]
[('mine', 'NN')]
[('sufficient', 'NN')]
[('ensure', 'VB')]
[('safety', 'NN')]
[('security', 'NN')]
[('job', 'NN')]
[('especially', 'RB')]
[('night', 'NN')]
[('hour', 'NN')]
[('make', 'VB')]
[('liberia', 'NN')]
[('attractive', 'JJ')]
[('favorable', 'JJ')]
[('destination', 'NN')]
[('foreign', 'JJ')]
[('direct', 'JJ')]
[('investment', 'NN')]
[('government', 'NN')]
[('liberia', 'NN')]
[('need', 'NN')]
[('seize', 'NN')]
[('responsibility', 'NN')]
[('providing', 'VBG')]
[('stationed', 'VBN')]
[('security', 'NN')]
[('present', 'NN')]
[('area', 'NN')]
[('concessionaire', 'NN')]
[('operating', 'NN')]
[('protect', 'NN')]
[('investment', 'NN')]
[('safety', 'NN')]
[('employee', 'NN')]
[('looking', 'VBG')]
[('company', 'NN')]
[('eke', 'NN')]
[('living', 'NN')]
[('putting', 'VBG')]
[('bread', 'NN')]
[('table', 'NN')]
[('family', 'NN')]
[('recent', 'JJ')]
[('u', 'NN')]
[('investment', 'NN')]
[('climate', 'NN')]
[('report', 'NN')]
[('liberia', 'NN')]
[('favorable', 'JJ')]
[('one', 'CD')]
[('country', 'NN')]
[('recent', 'JJ')]
[('repeated', 'VBN')]
[('attack', 'NN')]
[('aml', 'NN')]
[('troubling', 'VBG')]
[('investment', 'NN')]
[('climate', 'NN')]
[('potential', 'JJ')]
[('riddle', 'NN')]
[('liberia', 'NN')]
[('investment', 'NN')]
[('image', 'NN')]
[('beyond', 'IN')]
[('recent', 'JJ')]
[('u', 'NN')]
[('investment', 'NN')]
[('climate', 'NN')]
[('report', 'NN')]
[('liberia', 'NN')]
[('therefore', 'RB')]
[('government', 'NN')]
[('guarantee', 'NN')]
[('investor', 'NN')]
[('investment', 'NN')]
[('country', 'NN')]
[('paint', 'NN')]
[('positive', 'JJ')]
[('investment', 'NN')]
[('climate', 'NN')]
[('liberia', 'NN')]
[('discouraging', 'VBG')]
[('attack', 'NN')]

In [47]:
#Get pos_tag of all fake news
pos_tag_fake=[]
pos_tag_real=[]
for index, r in df_news.iterrows():
  if r['Label']==0:
    for w in r['content_lemmatised'].split(" "):
      pos_tag_f=nltk.pos_tag([w])
      pos_tag_fake.append(pos_tag_f)
  if r['Label']==1:
    for w in r['content_lemmatised'].split(" "):
      pos_tag_r=nltk.pos_tag([w])
      pos_tag_real.append(pos_tag_r)

In [54]:
pos_tag_real

[[('last', 'JJ')],
 [('week', 'NN')],
 [('armed', 'VBN')],
 [('men', 'NNS')],
 [('carrying', 'VBG')],
 [('machete', 'NN')],
 [('deadly', 'RB')],
 [('weapon', 'NN')],
 [('attacked', 'VBN')],
 [('arcelormittals', 'NNS')],
 [('tokadeh', 'NN')],
 [('mine', 'NN')],
 [('yekepa', 'NN')],
 [('shot', 'NN')],
 [('employee', 'NN')],
 [('violent', 'NN')],
 [('attack', 'NN')],
 [('masterminded', 'VBN')],
 [('gang', 'NN')],
 [('criminal', 'JJ')],
 [('said', 'VBD')],
 [('stationed', 'VBN')],
 [('town', 'NN')],
 [('zolowee', 'NN')],
 [('within', 'IN')],
 [('confines', 'NNS')],
 [('arcelormittals', 'NNS')],
 [('operational', 'JJ')],
 [('area', 'NN')],
 [('nimba', 'NN')],
 [('county', 'NN')],
 [('criminal', 'JJ')],
 [('earlier', 'RBR')],
 [('opened', 'VBN')],
 [('fire', 'NN')],
 [('police', 'NNS')],
 [('officer', 'NN')],
 [('town', 'NN')],
 [('officer', 'NN')],
 [('discovered', 'VBN')],
 [('warehouse', 'NN')],
 [('stolen', 'VBN')],
 [('fuel', 'NN')],
 [('oil', 'NN')],
 [('yellow', 'NN')],
 [('machine', 'NN')],
 [('spare', 'NN')],
 [('part', 'NN')],
 [('flogged', 'VBN')],
 [('segal', 'NN')],
 [('private', 'JJ')],
 [('security', 'NN')],
 [('guard', 'NN')],
 [('duty', 'NN')],
 [('damaged', 'VBN')],
 [('vehicle', 'NN')],
 [('attack', 'NN')],
 [('tokadeh', 'NN')],
 [('mine', 'NN')],
 [('arcelormittal', 'NN')],
 [('liberia', 'NN')],
 [('aml', 'NN')],
 [('confirmed', 'VBN')],
 [('situation', 'NN')],
 [('continue', 'NN')],
 [('work', 'NN')],
 [('ensure', 'VB')],
 [('safety', 'NN')],
 [('wellbeing', 'VBG')],
 [('emplyoees', 'NNS')],
 [('remain', 'NN')],
 [('top', 'NN')],
 [('priority', 'NN')],
 [('since', 'IN')],
 [('volent', 'NN')],
 [('gang', 'NN')],
 [('attack', 'NN')],
 [('mounting', 'VBG')],
 [('fear', 'NN')],
 [('uncertainty', 'NN')],
 [('engulfed', 'NN')],
 [('community', 'NN')],
 [('around', 'IN')],
 [('arcelormittals', 'NNS')],
 [('mining', 'NN')],
 [('site', 'NN')],
 [('nimba', 'NN')],
 [('county', 'NN')],
 [('people', 'NNS')],
 [('zolowee', 'NN')],
 [('town', 'NN')],
 [('gang', 'NN')],
 [('opened', 'VBN')],
 [('gun', 'NN')],
 [('fire', 'NN')],
 [('police', 'NNS')],
 [('officer', 'NN')],
 [('beat', 'NN')],
 [('private', 'JJ')],
 [('security', 'NN')],
 [('guard', 'NN')],
 [('even', 'RB')],
 [('terrified', 'VBN')],
 [('given', 'VBN')],
 [('shock', 'NN')],
 [('last', 'JJ')],
 [('week', 'NN')],
 [('event', 'NN')],
 [('disturbing', 'VBG')],
 [('fact', 'NN')],
 [('first', 'RB')],
 [('kind', 'NN')],
 [('company', 'NN')],
 [('come', 'VB')],
 [('repeated', 'VBN')],
 [('attack', 'NN')],
 [('criminal', 'JJ')],
 [('gang', 'NN')],
 [('government', 'NN')],
 [('liberia', 'NN')],
 [('step', 'NN')],
 [('immediately', 'RB')],
 [('provide', 'NN')],
 [('security', 'NN')],
 [('biggest', 'JJS')],
 [('foreign', 'JJ')],
 [('direct', 'JJ')],
 [('investment', 'NN')],
 [('country', 'NN')],
 [('ensure', 'VB')],
 [('safety', 'NN')],
 [('company', 'NN')],
 [('employee', 'NN')],
 [('well', 'RB')],
 [('company', 'NN')],
 [('property', 'NN')],
 [('acelormittal', 'NN')],
 [('several', 'JJ')],
 [('year', 'NN')],
 [('biggest', 'JJS')],
 [('taxpayer', 'NN')],
 [('government', 'NN')],
 [('apart', 'RB')],
 [('mda', 'NN')],
 [('responsibility', 'NN')],
 [('demonstrated', 'VBN')],
 [('ample', 'NN')],
 [('commitment', 'NN')],
 [('patriotism', 'NN')],
 [('country', 'NN')],
 [('providing', 'VBG')],
 [('support', 'NN')],
 [('critical', 'JJ')],
 [('area', 'NN')],
 [('health', 'NN')],
 [('education', 'NN')],
 [('infrastructure', 'NN')],
 [('sport', 'NN')],
 [('etc', 'NN')],
 [('last', 'JJ')],
 [('two', 'CD')],
 [('year', 'NN')],
 [('liberia', 'NN')],
 [('revenue', 'NN')],
 [('authority', 'NN')],
 [('awarded', 'VBN')],
 [('aml', 'NN')],
 [('country', 'NN')],
 [('biggest', 'JJS')],
 [('taxpayer', 'NN')],
 [('tax', 'NN')],
 [('compliant', 'NN')],
 [('recent', 'JJ')],
 [('attack', 'NN')],
 [('company', 'NN')],
 [('mining', 'NN')],
 [('site', 'NN')],
 [('nimba', 'NN')],
 [('instilling', 'VBG')],
 [('wonton', 'NN')],
 [('fear', 'NN')],
 [('among', 'IN')],
 [('several', 'JJ')],
 [('employee', 'NN')],
 [('resident', 'NN')],
 [('nearby', 'RB')],
 [('community', 'NN')],
 [('speculated', 'VBN')],
 [('incident', 'NN')],
 [('took', 'VBD')],
 [('place', 'NN')],
 [('company', 'NN')],
 [('employee', 'NN')],
 [('assigned', 'VBN')],
 [('tokodehs', 'NN')],
 [('mining', 'NN')],
 [('site', 'NN')],
 [('nimba', 'NN')],
 [('county', 'NN')],
 [('reluctantly', 'RB')],
 [('showing', 'VBG')],
 [('job', 'NN')],
 [('due', 'JJ')],
 [('fear', 'NN')],
 [('criminal', 'JJ')],
 [('may', 'MD')],
 [('return', 'NN')],
 [('harm', 'NN')],
 [('life', 'NN')],
 [('security', 'NN')],
 [('officer', 'NN')],
 [('assigned', 'VBN')],
 [('mine', 'NN')],
 [('sufficient', 'NN')],
 [('ensure', 'VB')],
 [('safety', 'NN')],
 [('security', 'NN')],
 [('job', 'NN')],
 [('especially', 'RB')],
 [('night', 'NN')],
 [('hour', 'NN')],
 [('make', 'VB')],
 [('liberia', 'NN')],
 [('attractive', 'JJ')],
 [('favorable', 'JJ')],
 [('destination', 'NN')],
 [('foreign', 'JJ')],
 [('direct', 'JJ')],
 [('investment', 'NN')],
 [('government', 'NN')],
 [('liberia', 'NN')],
 [('need', 'NN')],
 [('seize', 'NN')],
 [('responsibility', 'NN')],
 [('providing', 'VBG')],
 [('stationed', 'VBN')],
 [('security', 'NN')],
 [('present', 'NN')],
 [('area', 'NN')],
 [('concessionaire', 'NN')],
 [('operating', 'NN')],
 [('protect', 'NN')],
 [('investment', 'NN')],
 [('safety', 'NN')],
 [('employee', 'NN')],
 [('looking', 'VBG')],
 [('company', 'NN')],
 [('eke', 'NN')],
 [('living', 'NN')],
 [('putting', 'VBG')],
 [('bread', 'NN')],
 [('table', 'NN')],
 [('family', 'NN')],
 [('recent', 'JJ')],
 [('u', 'NN')],
 [('investment', 'NN')],
 [('climate', 'NN')],
 [('report', 'NN')],
 [('liberia', 'NN')],
 [('favorable', 'JJ')],
 [('one', 'CD')],
 [('country', 'NN')],
 [('recent', 'JJ')],
 [('repeated', 'VBN')],
 [('attack', 'NN')],
 [('aml', 'NN')],
 [('troubling', 'VBG')],
 [('investment', 'NN')],
 [('climate', 'NN')],
 [('potential', 'JJ')],
 [('riddle', 'NN')],
 [('liberia', 'NN')],
 [('investment', 'NN')],
 [('image', 'NN')],
 [('beyond', 'IN')],
 [('recent', 'JJ')],
 [('u', 'NN')],
 [('investment', 'NN')],
 [('climate', 'NN')],
 [('report', 'NN')],
 [('liberia', 'NN')],
 [('therefore', 'RB')],
 [('government', 'NN')],
 [('guarantee', 'NN')],
 [('investor', 'NN')],
 [('investment', 'NN')],
 [('country', 'NN')],
 [('paint', 'NN')],
 [('positive', 'JJ')],
 [('investment', 'NN')],
 [('climate', 'NN')],
 [('liberia', 'NN')],
 [('discouraging', 'VBG')],
 [('attack', 'NN')],
 [('amid', 'IN')],
 [('recent', 'JJ')],
 [('coup', 'NN')],
 [('niger', 'NN')],
 [('chief', 'NN')],
 [('staff', 'NN')],
 [('liberian', 'JJ')],
 [('army', 'NN')],
 [('armed', 'VBN')],
 [('force', 'NN')],
 [('liberia', 'NN')],
 [('majgen', 'NN')],
 [('charles', 'NNS')],
 [('johnson', 'NN')],
 [('iii', 'NN')],
 [('recommending', 'VBG')],
 [('reduction', 'NN')],
 [('presidential', 'JJ')],
 [('guard', 'NN')],
 [('order', 'NN')],
 [('drastically', 'RB')],
 [('reduce', 'VB')],
 [('unforeseen', 'JJ')],
 [('coup', 'NN')],
 [('subregion', 'NN')],
 [('prevent', 'NN')],
 [('incidence', 'NN')],
 [('coup', 'NN')],
 [('detat', 'NN')],
 [('liberian', 'JJ')],
 [('army', 'NN')],
 [('chief', 'NN')],
 [('staff', 'NN')],
 [('made', 'VBN')],
 [('known', 'VBN')],
 [('speaking', 'VBG')],
 [('journalist', 'NN')],
 [('thursday', 'NN')],
 [('sideline', 'NN')],
 [('joint', 'NN')],
 [('delocalized', 'VBN')],
 [('meeting', 'NN')],
 [('ecowas', 'NN')],
 [('parliament', 'NN')],
 [('joint', 'NN')],
 [('committee', 'NN')],
 [('political', 'JJ')],
 [('affair', 'NN')],
 [('peace', 'NN')],
 [('security', 'NN')],
 [('african', 'JJ')],
 [('peer', 'NN')],
 [('review', 'NN')],
 [('mechanism', 'NN')],
 [('judicial', 'NN')],
 [('affair', 'NN')],
 [('human', 'NN')],
 [('right', 'NN')],
 [('social', 'JJ')],
 [('affair', 'NN')],
 [('gender', 'NN')],
 [('woman', 'NN')],
 [('empowerment', 'NN')],
 [('monrovia', 'NN')],
 [('said', 'VBD')],
 [('member', 'NN')],
 [('state', 'NN')],
 [('must', 'MD')],
 [('mindful', 'NN')],
 [('much', 'JJ')],
 [('control', 'NN')],
 [('military', 'JJ')],
 [('following', 'VBG')],
 [('coup', 'NN')],
 [('detat', 'NN')],
 [('ousted', 'VBN')],
 [('president', 'NN')],
 [('mohamed', 'VBN')],
 [('bazoum', 'NN')],
 [('niger', 'NN')],
 [('power', 'NN')],
 [('wednesday', 'NN')],
 [('johnson', 'NN')],
 [('earlier', 'RBR')],
 [('delivered', 'VBN')],
 [('paper', 'NN')],
 [('topic', 'NN')],
 [('role', 'NN')],
 [('armed', 'VBN')],
 [('security', 'NN')],
 [('force', 'NN')],
 [('political', 'JJ')],
 [('government', 'NN')],
 [('case', 'NN')],
 [('mail', 'NN')],
 [('burkina', 'NN')],
 [('faso', 'NN')],
 [('guinea', 'NN')],
 [('lesson', 'NN')],
 [('learned', 'VBN')],
 [('prospect', 'NN')],
 [('second', 'JJ')],
 [('recommendation', 'NN')],
 [('issue', 'NN')],
 [('presidential', 'JJ')],
 [('guard', 'NN')],
 [('elite', 'NN')],
 [('force', 'NN')],
 [('direct', 'JJ')],
 [('control', 'NN')],
 [('commander', 'NN')],
 [('chief', 'NN')],
 [('look', 'NN')],
 [('happening', 'VBG')],
 [('even', 'RB')],
 [('niger', 'NN')],
 [('yesterday', 'NN')],
 [('presidential', 'JJ')],
 [('guard', 'NN')],
 [('look', 'NN')],
 [('history', 'NN')],
 [('liberia', 'NN')],
 [('seen', 'VBN')],
 [('issue', 'NN')],
 [('presidential', 'JJ')],
 [('guard', 'NN')],
 [('misused', 'VBN')],
 [('peace', 'NN')],
 [('reconciliation', 'NN')],
 [('report', 'NN')],
 [('say', 'VB')],
 [('special', 'JJ')],
 [('antiterrorism', 'NN')],
 [('unit', 'NN')],
 [('involved', 'VBN')],
 [('lot', 'NN')],
 [('alleged', 'VBN')],
 [('atrocity', 'NN')],
 [('according', 'VBG')],
 [('report', 'NN')],
 [('emphasized', 'VBN')],
 [('need', 'NN')],
 [('mindful', 'NN')],
 [('allow', 'VB')],
 [('military', 'JJ')],
 [('control', 'NN')],
 [('political', 'JJ')],
 [('interference', 'NN')],
 [('command', 'NN')],
 [('control', 'NN')],
 [('military', 'JJ')],
 [('presidential', 'JJ')],
 [('guard', 'NN')],
 [('commander', 'NN')],
 [('chief', 'NN')],
 [('selecting', 'VBG')],
 [('somebody', 'NN')],
 [('head', 'NN')],
 [('instead', 'RB')],
 [('allowing', 'VBG')],
 [('cd', 'NN')],
 [('chief', 'NN')],
 [('defense', 'NN')],
 [('staff', 'NN')],
 [('d', 'NN')],
 [('go', 'VB')],
 [('process', 'NN')],
 [('somebody', 'NN')],
 [('control', 'NN')],
 [('becomes', 'NNS')],
 [('problem', 'NN')],
 [('cd', 'NN')],
 [('chief', 'NN')],
 [('staff', 'NN')],
 [('control', 'NN')],
 [('unit', 'NN')],
 [('take', 'VB')],
 [('direct', 'JJ')],
 [('control', 'NN')],
 [('commander', 'NN')],
 [('chief', 'NN')],
 [('said', 'VBD')],
 [('johnson', 'NN')],
 [('iii', 'NN')],
 [('said', 'VBD')],
 [('justification', 'NN')],
 [('military', 'JJ')],
 [('coup', 'NN')],
 [('matter', 'NN')],
 [('situation', 'NN')],
 [('justification', 'NN')],
 [('military', 'JJ')],
 [('coup', 'NN')],
 [('happening', 'VBG')],
 [('absolutely', 'RB')],
 [('notjohnson', 'NN')],
 [('added', 'VBD')],
 [('liberian', 'JJ')],
 [('major', 'JJ')],
 [('general', 'JJ')],
 [('advocated', 'VBN')],
 [('dialogue', 'NN')],
 [('embattled', 'VBN')],
 [('country', 'NN')],
 [('noting', 'VBG')],
 [('sanction', 'NN')],
 [('best', 'JJS')],
 [('way', 'NN')],
 [('resolve', 'NN')],
 [('crisis', 'NN')],
 [('said', 'VBD')],
 [('terrorism', 'NN')],
 [('adequately', 'RB')],
 [('fought', 'NN')],
 [('country', 'NN')],
 [('kept', 'NN')],
 [('aside', 'RB')],
 [('adding', 'VBG')],
 [('suspending', 'VBG')],
 [('pose', 'NN')],
 [('threat', 'NN')],
 [('especially', 'RB')],
 [('border', 'NN')],
 [('country', 'NN')],
 [('last', 'JJ')],
 [('recommendation', 'NN')],
 [('need', 'NN')],
 [('dialogue', 'NN')],
 [('fight', 'NN')],
 [('terrorism', 'NN')],
 [('suspend', 'NN')],
 [('country', 'NN')],
 [('border', 'NN')],
 [('guinea', 'NN')],
 [('need', 'NN')],
 [('protect', 'NN')],
 [('borderland', 'NN')],
 [('liberia', 'NN')],
 [('guinea', 'NN')],
 [('head', 'NN')],
 [('state', 'NN')],
 [('go', 'VB')],
 [('ahead', 'RB')],
 [('sanction', 'NN')],
 [('still', 'RB')],
 [('allow', 'VB')],
 [('work', 'NN')],
 [('guinea', 'NN')],
 [('working', 'VBG')],
 [('guinea', 'NN')],
 [('going', 'VBG')],
 [('difficult', 'JJ')],
 [('recommended', 'VBN')],
 [('still', 'RB')],
 [('need', 'NN')],
 [('dialogue', 'NN')],
 [('johnson', 'NN')],
 [('iii', 'NN')],
 [('said', 'VBD')],
 [('military', 'JJ')],
 [('must', 'MD')],
 [('stick', 'NN')],
 [('mandate', 'NN')],
 [('protecting', 'VBG')],
 [('nation', 'NN')],
 [('interfere', 'RB')],
 [('governance', 'NN')],
 [('group', 'NN')],
 [('unknown', 'JJ')],
 [('men', 'NNS')],
 [('said', 'VBD')],
 [('zolowee', 'NN')],
 [('town', 'NN')],
 [('proximity', 'NN')],
 [('arcelormittals', 'NNS')],
 [('concession', 'NN')],
 [('area', 'NN')],
 [('attacked', 'VBN')],
 [('arcelormittals', 'NNS')],
 [('tokadeh', 'NN')],
 [('mine', 'NN')],
 [('yekepa', 'NN')],
 [('nimba', 'NN')],
 [('county', 'NN')],
 [('esrly', 'RB')],
 [('friday', 'NN')],
 [('gang', 'NN')],
 [('armed', 'VBN')],
 [('single', 'JJ')],
 [('barrelguns', 'NNS')],
 [('pistol', 'NN')],
 [('seen', 'VBN')],
 [('carrying', 'VBG')],
 [('machete', 'NN')],
 [('arcelormittal', 'NN')],
 [('statement', 'NN')],
 [('issued', 'VBN')],
 [('today', 'NN')],
 [('confirmed', 'VBN')],
 [('one', 'CD')],
 [('employee', 'NN')],
 [('shot', 'NN')],
 [('wounded', 'VBD')],
 [('attack', 'NN')],
 [('said', 'VBD')],
 [('stable', 'JJ')],
 [('condition', 'NN')],
 [('gang', 'NN')],
 [('ransacked', 'VBN')],
 [('damaged', 'VBN')],
 [('crusher', 'NN')],
 [('plant', 'NN')],
 [('control', 'NN')],
 [('room', 'NN')],
 [('vehicle', 'NN')],
 [('large', 'JJ')],
 [('welding', 'VBG')],
 [('machine', 'NN')],
 [('reporter', 'NN')],
 [('visited', 'VBN')],
 [('scene', 'NN')],
 [('said', 'VBD')],
 [('attack', 'NN')],
 [('amls', 'NN')],
 [('mine', 'NN')],
 [('tokadeh', 'NN')],
 [('mine', 'NN')],
 [('caused', 'VBN')],
 [('panic', 'NN')],
 [('amongst', 'NN')],
 [('worker', 'NN')],
 [('resident', 'NN')],
 [('demanding', 'VBG')],
 [('national', 'JJ')],
 [('government', 'NN')],
 [('provide', 'NN')],
 [('security', 'NN')],
 [('area', 'NN')],
 [('liberia', 'NN')],
 [('national', 'JJ')],
 [('police', 'NNS')],
 [('eru', 'NN')],
 [('assigned', 'VBN')],
 [('yekepa', 'NN')],
 [('support', 'NN')],
 [('gbarnga', 'NN')],
 [('bong', 'NN')],
 [('county', 'NN')],
 [('swiftly', 'RB')],
 [('responded', 'VBD')],
 [('apprehended', 'VBD')],
 [('suspect', 'NN')],
 [('restored', 'VBN')],
 [('calm', 'NN')],
 [('mine', 'NN')],
 [('report', 'NN')],
 [('say', 'VB')],
 [('tokadeh', 'NN')],
 [('gangra', 'NN')],
 [('mine', 'NN')],
 [('appear', 'VB')],
 [('closed', 'VBD')],
 [('unconfirmed', 'JJ')],
 [('report', 'NN')],
 [('say', 'VB')],
 [('one', 'CD')],
 [('police', 'NNS')],
 [('eru', 'NN')],
 [('injured', 'JJ')],
 [('lost', 'VBN')],
 [('tip', 'NN')],
 [('three', 'CD')],
 [('finger', 'NN')],
 [('exchange', 'NN')],
 [('fire', 'NN')],
 [('attacker', 'NN')],
 [('aml', 'NN')],
 [('statement', 'NN')],
 [('strongly', 'RB')],
 [('condemned', 'VBN')],
 [('attack', 'NN')],
 [('said', 'VBD')],
 [('contacted', 'VBN')],
 [('ministry', 'NN')],
 [('justice', 'NN')],
 [('mine', 'NN')],
 [('energy', 'NN')],
 [('full', 'JJ')],
 [('investigation', 'NN')],
 [('attack', 'NN')],
 [('operation', 'NN')],
 [('prosecution', 'NN')],
 [('involved', 'VBN')],
 [('said', 'VBD')],
 [('statement', 'NN')],
 [('arcelormittal', 'NN')],
 [('liberia', 'NN')],
 [('aml', 'NN')],
 [('confirm', 'NN')],
 [('july', 'NN')],
 [('tokadeh', 'NN')],
 [('mine', 'NN')],
 [('attacked', 'VBN')],
 [('group', 'NN')],
 [('unknown', 'JJ')],
 [('individual', 'JJ')],
 [('bearing', 'NN')],
 [('arm', 'NN')],
 [('machete', 'NN')],
 [('aml', 'NN')],
 [('regret', 'NN')],
 [('report', 'NN')],
 [('one', 'CD')],
 [('employee', 'NN')],
 [('shot', 'NN')],
 [('wounded', 'VBD')],
 [('condition', 'NN')],
 [('remains', 'NNS')],
 [('stable', 'JJ')],
 [('continue', 'NN')],
 [('closely', 'RB')],
 [('monitored', 'VBD')],
 [('company', 'NN')],
 [('doctor', 'NN')],
 [('added', 'VBD')],
 [('aml', 'NN')],
 [('strongly', 'RB')],
 [('condemns', 'NN')],
 [('violence', 'NN')],
 [('kind', 'NN')],
 [('staff', 'NN')],
 [('member', 'NN')],
 [('continue', 'NN')],
 [('work', 'NN')],
 [('ensure', 'VB')],
 [('safety', 'NN')],
 [('wellbeing', 'VBG')],
 [('employee', 'NN')],
 [('remain', 'NN')],
 [('top', 'NN')],
 [('priority', 'NN')],
 [('source', 'NN')],
 [('say', 'VB')],
 [('wellestablished', 'VBN')],
 [('organized', 'VBN')],
 [('gang', 'NN')],
 [('criminal', 'JJ')],
 [('syndicate', 'NN')],
 [('involved', 'VBN')],
 [('regular', 'JJ')],
 [('theft', 'NN')],
 [('diesel', 'NN')],
 [('fuel', 'NN')],
 [('spare', 'NN')],
 [('part', 'NN')],
 [('aml', 'NN')],
 [('mine', 'NN')],
 [('incident', 'NN')],
 [('began', 'VBD')],
 [('shortly', 'RB')],
 [('police', 'NNS')],
 [('executed', 'VBN')],
 [('search', 'NN')],
 [('warrant', 'NN')],
 [('discovered', 'VBN')],
 [('warehouse', 'NN')],
 [('zolowee', 'NN')],
 [('stocked', 'VBN')],
 [('fuel', 'NN')],
 [('caterpillar', 'NN')],
 [('spare', 'NN')],
 [('part', 'NN')],
 [('apparently', 'RB')],
 [('stolen', 'VBN')],
 [('aml', 'NN')],
 [('company', 'NN')],
 [('recently', 'RB')],
 [('started', 'VBN')],
 [('adding', 'VBG')],
 [('coloring', 'VBG')],
 [('fuel', 'NN')],
 [('discourage', 'NN')],
 [('theft', 'NN')],
 [('day', 'NN')],
 [('earlier', 'RBR')],
 [('several', 'JJ')],
 [('suspect', 'NN')],
 [('arrested', 'VBN')],
 [('opened', 'VBN')],
 [('fire', 'NN')],
 [('police', 'NNS')],
 [('officer', 'NN')],
 [('town', 'NN')],
 [('zolowee', 'NN')],
 [('one', 'CD')],
 [('police', 'NNS')],
 [('officer', 'NN')],
 [('said', 'VBD')],
 [('sustained', 'VBN')],
 [('injury', 'NN')],
 [('eyewitness', 'NN')],
 [('say', 'VB')],
 [('criminal', 'JJ')],
 [('severely', 'RB')],
 [('beat', 'NN')],
 [('segal', 'NN')],
 [('security', 'NN')],
 [('officer', 'NN')],
 [('assigned', 'VBN')],
 [('area', 'NN')],
 [('damaged', 'VBN')],
 [('vehicle', 'NN')],
 [('ministry', 'NN')],
 [('justice', 'NN')],
 [('lnp', 'NN')],
 [('commented', 'VBN')],
 [('incident', 'NN')],
 [('press', 'NN')],
 [('time', 'NN')],
 [('liberian', 'JJ')],
 [('president', 'NN')],
 [('george', 'NN')],
 [('weah', 'NN')],
 [('pledged', 'VBN')],
 [('deliver', 'NN')],
 [('violent', 'NN')],
 [('free', 'JJ')],
 [('credible', 'JJ')],
 [('transparent', 'NN')],
 [('inclusive', 'JJ')],
 [('election', 'NN')],
 [('country', 'NN')],
 [('prepares', 'NNS')],
 [('presidential', 'JJ')],
 [('general', 'JJ')],
 [('election', 'NN')],
 [('october', 'NN')],
 [('president', 'NN')],
 [('weah', 'NN')],
 [('made', 'VBN')],
 [('commitment', 'NN')],
 [('wednesday', 'NN')],
 [('monrovia', 'NN')],
 [('commemoration', 'NN')],
 [('th', 'NN')],
 [('independence', 'NN')],
 [('country', 'NN')],
 [('theme', 'NN')],
 [('giving', 'VBG')],
 [('people', 'NNS')],
 [('hope', 'NN')],
 [('violence', 'NN')],
 [('free', 'JJ')],
 [('fair', 'NN')],
 [('transparent', 'NN')],
 [('inclusive', 'JJ')],
 [('credible', 'JJ')],
 [('election', 'NN')],
 [('weah', 'NN')],
 [('said', 'VBD')],
 [('theme', 'NN')],
 [('year', 'NN')],
 [('celebration', 'NN')],
 [('special', 'JJ')],
 [('significance', 'NN')],
 [('come', 'VB')],
 [('heel', 'NN')],
 [('nation', 'NN')],
 [('election', 'NN')],
 [('reiterating', 'VBG')],
 [('commitment', 'NN')],
 [('uphold', 'JJ')],
 [('preserve', 'NN')],
 [('peaceful', 'NN')],
 [('democracy', 'NN')],
 [('liberia', 'NN')],
 [('today', 'NN')],
 [('collective', 'NN')],
 [('duty', 'NN')],
 [('uphold', 'JJ')],
 [('defend', 'NN')],
 [('constitution', 'NN')],
 [('pledge', 'NN')],
 [('ability', 'NN')],
 [('theme', 'NN')],
 [('year', 'NN')],
 [('celebration', 'NN')],
 [('reminder', 'NN')],
 [('duty', 'NN')],
 [('country', 'NN')],
 [('god', 'NN')],
 [('reiterate', 'NN')],
 [('commitment', 'NN')],
 [('preserving', 'VBG')],
 [('peace', 'NN')],
 [('country', 'NN')],
 [('sustained', 'VBN')],
 [('singing', 'VBG')],
 [('comprehensive', 'NN')],
 [('peace', 'NN')],
 [('agreement', 'NN')],
 [('cpa', 'NN')],
 [('aug', 'NN')],
 [('accra', 'NN')],
 [('ghana', 'NN')],
 [('presidential', 'JJ')],
 [('general', 'JJ')],
 [('election', 'NN')],
 [('credible', 'JJ')],
 [('reflect', 'NN')],
 [('voice', 'NN')],
 [('people', 'NNS')],
 [('liberia', 'NN')],
 [('meet', 'NN')],
 [('international', 'JJ')],
 [('national', 'JJ')],
 [('standardsweah', 'NN')],
 [('said', 'VBD')],
 [('weah', 'NN')],
 [('admonished', 'VBN')],
 [('politician', 'NN')],

In [55]:
nnpwords_real=[]
for item in pos_tag_real:
  if item[0][1] in ['NNP', 'NNPS']:
    nnpwords_real.append(item[0][0])
nnp_real=Counter(nnpwords_real)
nnp_real.most_common(100)

[]

In [20]:
nnpwords_fake=[]
for item in pos_tag_fake:
  if item[0][1] in ['NNP', 'NNPS']:
    nnpwords_fake.append(item[0][0])
nnp_fake=Counter(nnpwords_fake)
nnp_fake.most_common(100)

[('March', 5461),
 ('April', 4279),
 ('Health', 3517),
 ('May', 2934),
 ('President', 2895),
 ('Africa', 2177),
 ('South', 1885),
 ('February', 1732),
 ('July', 1697),
 ('National', 1625),
 ('Ghana', 1608),
 ('June', 1595),
 ('University', 1558),
 ('United', 1481),
 ('January', 1412),
 ('CDC', 1175),
 ('Media', 1171),
 ('George', 1043),
 ('Department', 1016),
 ('November', 946),
 ('ANC', 929),
 ('International', 915),
 ('August', 894),
 ('October', 888),
 ('Social', 873),
 ('December', 867),
 ('September', 849),
 ('Kenya', 842),
 ('Minister', 818),
 ('Center', 752),
 ('New', 703),
 ('Buhari', 608),
 ('Institute', 606),
 ('Johnson', 593),
 ('Act', 592),
 ('White', 587),
 ('Party', 578),
 ('Ministry', 551),
 ('City', 521),
 ('District', 486),
 ('Service', 474),
 ('Congress', 469),
 ('Washington', 460),
 ('Group', 448),
 ('West', 444),
 ('Court', 437),
 ('Journal', 425),
 ('Bank', 418),
 ('Commission', 412),
 ('County', 409),
 ('Development', 381),
 ('Peter', 370),
 ('Kenyan', 359),
 ('Monday', 354),
 ('BnnWashington', 350),
 ('China', 328),
 ('Burkina', 323),
 ('Friday', 310),
 ('Louis', 308),
 ('FDA', 307),
 ('Sunday', 304),
 ('Thursday', 303),
 ('Senate', 301),
 ('Inc', 298),
 ('Vice', 295),
 ('France', 288),
 ('Jeffrey', 287),
 ('General', 286),
 ('Association', 285),
 ('Prime', 284),
 ('California', 282),
 ('Human', 273),
 ('Tuesday', 270),
 ('Kenyas', 264),
 ('SA', 262),
 ('Maxwell', 257),
 ('Canada', 254),
 ('Professor', 254),
 ('John', 253),
 ('America', 249),
 ('London', 248),
 ('Wednesday', 241),
 ('Secretary', 239),
 ('God', 237),
 ('Biden', 237),
 ('House', 225),
 ('Kano', 224),
 ('Europe', 215),
 ('Coast', 207),
 ('Korea', 205),
 ('Buharis', 205),
 ('Florida', 201),
 ('Ahmed', 201),
 ('Street', 200),
 ('Day', 200),
 ('Saturday', 198),
 ('Supreme', 197),
 ('Bola', 196),
 ('Kenyatta', 190),
 ('Angeles', 187)]

In [22]:
#Save to dataframe
df_nnp_real=pd.DataFrame(nnp_real.most_common(212))
df_nnp_real['news_category']=1
df_nnp_real=df_nnp_real.rename(columns={0:'NNP', 1:'frequency'})
df_nnp_real['frequency_ratio']=(df_nnp_real['frequency']/len(nnpwords_real))*100

#Drop month proper nouns
import calendar
month_name=list(calendar.month_name)[1::]
df_nnp_real=df_nnp_real.loc[~df_nnp_real['NNP'].isin(month_name)]

df_nnp_real

              NNP  frequency  news_category  frequency_ratio
0       President      33287              1         6.291499
1          County      23343              1         4.412007
2        National      18287              1         3.456384
3        Minister      13199              1         2.494713
4        Ministry      12676              1         2.395861
..            ...        ...            ...              ...
207         Boima        239              1         0.045173
208  Barclayville        234              1         0.044228
209         Kogar        233              1         0.044039
210         Aaron        220              1         0.041582
211        Wesley        219              1         0.041393

[200 rows x 4 columns]

In [23]:
df_nnp_fake=pd.DataFrame(nnp_fake.most_common(212))
df_nnp_fake['news_category']=0
df_nnp_fake=df_nnp_fake.rename(columns={0:'NNP', 1:'frequency'})
df_nnp_fake['frequency_ratio']=(-df_nnp_fake['frequency']/len(nnpwords_fake))*100

#Drop month proper nouns
df_nnp_fake=df_nnp_fake.loc[~df_nnp_fake['NNP'].isin(month_name)]

df_nnp_fake

           NNP  frequency  news_category  frequency_ratio
2       Health       3517              0        -3.541900
4    President       2895              0        -2.915496
5       Africa       2177              0        -2.192413
6        South       1885              0        -1.898345
9     National       1625              0        -1.636505
..         ...        ...            ...              ...
207        Lee         57              0        -0.057404
208   Democrat         57              0        -0.057404
209     Macron         57              0        -0.057404
210   Vanguard         56              0        -0.056396
211  McConnell         56              0        -0.056396

[200 rows x 4 columns]

In [26]:
#Concatenate 2 dataframes
df_nnp=pd.concat([df_nnp_real, df_nnp_fake])
df_nnp

           NNP  frequency  news_category  frequency_ratio
0    President      33287              1         6.291499
1       County      23343              1         4.412007
2     National      18287              1         3.456384
3     Minister      13199              1         2.494713
4     Ministry      12676              1         2.395861
..         ...        ...            ...              ...
207        Lee         57              0        -0.057404
208   Democrat         57              0        -0.057404
209     Macron         57              0        -0.057404
210   Vanguard         56              0        -0.056396
211  McConnell         56              0        -0.056396

[400 rows x 4 columns]

In [27]:
#Reset index
df_nnp=df_nnp.reset_index()
df_nnp=df_nnp.drop(['index'], axis=1)
df_nnp

           NNP  frequency  news_category  frequency_ratio
0    President      33287              1         6.291499
1       County      23343              1         4.412007
2     National      18287              1         3.456384
3     Minister      13199              1         2.494713
4     Ministry      12676              1         2.395861
..         ...        ...            ...              ...
395        Lee         57              0        -0.057404
396   Democrat         57              0        -0.057404
397     Macron         57              0        -0.057404
398   Vanguard         56              0        -0.056396
399  McConnell         56              0        -0.056396

[400 rows x 4 columns]

In [28]:
#Save to csv
df_nnp.to_csv("/content/drive/My Drive/My Folder/nnp_200.csv")

In [56]:
#Function: count the occurrence of different tags in both fake and real news dataset
def get_pos_tag_count(pos_tag_list):
  tags=[]
  from collections import Counter
  for item in pos_tag_list:
    tags.append(item[0][1])
  tag_counts=Counter(tags)
  return tag_counts

In [57]:
list(get_pos_tag_count(pos_tag_fake).items())

[('VBG', 76099),
 ('NN', 1255391),
 ('JJ', 155450),
 ('NNS', 77057),
 ('RB', 63605),
 ('VB', 26407),
 ('VBN', 119669),
 ('JJS', 4222),
 ('IN', 17241),
 ('CD', 16681),
 ('VBZ', 2478),
 ('MD', 6451),
 ('JJR', 1731),
 ('DT', 3709),
 ('VBD', 33125),
 ('RBR', 1075),
 ('CC', 45),
 ('WP$', 318),
 ('WDT', 119),
 ('PRP', 230),
 ('WP', 174),
 ('VBP', 2)]

In [31]:
get_pos_tag_count(pos_tag_real)

Counter({'JJ': 619977,
         'NN': 3851529,
         'VBN': 430640,
         'NNS': 1159582,
         'VBG': 340711,
         'RB': 230697,
         'VBD': 147970,
         'IN': 76848,
         'NNP': 529027,
         'RBR': 8649,
         'VB': 105758,
         'JJS': 13834,
         'CD': 69589,
         'MD': 13424,
         'VBZ': 42308,
         'PRP': 7850,
         'JJR': 6410,
         'DT': 11435,
         'UH': 175,
         'WP$': 1631,
         'SYM': 1292,
         'CC': 1866,
         'WDT': 748,
         'NNPS': 52,
         'WRB': 83,
         'FW': 188,
         'WP': 34,
         'RBS': 12,
         'PRP$': 3})

In [32]:
df_pos_tag_fake=pd.DataFrame(list(get_pos_tag_count(pos_tag_fake).items()), columns=['pos_tag', 'frequency'])
df_pos_tag_fake['frequency_ratio']=100*(df_pos_tag_fake['frequency']/sum(df_pos_tag_fake['frequency']))
df_pos_tag_fake['news_category']=0
df_pos_tag_fake

   pos_tag  frequency  frequency_ratio  news_category
0      VBG      75637         4.063711              0
1       NN     951498        51.120654              0
2      NNS     293452        15.766148              0
3       JJ     140953         7.572911              0
4       RB      61921         3.326798              0
5      PRP        658         0.035352              0
6       VB      29016         1.558928              0
7      VBN     118901         6.388134              0
8      JJS       4345         0.233442              0
9       IN      17845         0.958749              0
10      CD      15783         0.847965              0
11     NNP      99024         5.320213              0
12     VBZ       7227         0.388281              0
13     RBR       1628         0.087467              0
14     JJR       1770         0.095096              0
15      DT       3648         0.195994              0
16     VBD      32944         1.769966              0
17      MD       3427         0.184121              0
18      UH        145         0.007790              0
19      CC        151         0.008113              0
20     SYM        371         0.019933              0
21     WP$        315         0.016924              0
22      WP         65         0.003492              0
23     WDT        111         0.005964              0
24      FW        138         0.007414              0
25     WRB         21         0.001128              0
26     RBS          6         0.000322              0
27    NNPS        273         0.014667              0
28    PRP$          6         0.000322              0

In [33]:
df_pos_tag_real=pd.DataFrame(list(get_pos_tag_count(pos_tag_real).items()), columns=['pos_tag', 'frequency'])
df_pos_tag_real['frequency_ratio']=100*(df_pos_tag_real['frequency']/sum(df_pos_tag_real['frequency']))
df_pos_tag_real['news_category']=1
df_pos_tag_real

   pos_tag  frequency  frequency_ratio  news_category
0       JJ     619977         8.080696              1
1       NN    3851529        50.200304              1
2      VBN     430640         5.612903              1
3      NNS    1159582        15.113834              1
4      VBG     340711         4.440781              1
5       RB     230697         3.006873              1
6      VBD     147970         1.928621              1
7       IN      76848         1.001626              1
8      NNP     529027         6.895266              1
9      RBR       8649         0.112730              1
10      VB     105758         1.378435              1
11     JJS      13834         0.180310              1
12      CD      69589         0.907014              1
13      MD      13424         0.174967              1
14     VBZ      42308         0.551437              1
15     PRP       7850         0.102316              1
16     JJR       6410         0.083547              1
17      DT      11435         0.149042              1
18      UH        175         0.002281              1
19     WP$       1631         0.021258              1
20     SYM       1292         0.016840              1
21      CC       1866         0.024321              1
22     WDT        748         0.009749              1
23    NNPS         52         0.000678              1
24     WRB         83         0.001082              1
25      FW        188         0.002450              1
26      WP         34         0.000443              1
27     RBS         12         0.000156              1
28    PRP$          3         0.000039              1

In [34]:
#Concatenate two DataFrames
df_pos_tag=pd.concat([df_pos_tag_real, df_pos_tag_fake])
df_pos_tag

   pos_tag  frequency  frequency_ratio  news_category
0       JJ     619977         8.080696              1
1       NN    3851529        50.200304              1
2      VBN     430640         5.612903              1
3      NNS    1159582        15.113834              1
4      VBG     340711         4.440781              1
5       RB     230697         3.006873              1
6      VBD     147970         1.928621              1
7       IN      76848         1.001626              1
8      NNP     529027         6.895266              1
9      RBR       8649         0.112730              1
10      VB     105758         1.378435              1
11     JJS      13834         0.180310              1
12      CD      69589         0.907014              1
13      MD      13424         0.174967              1
14     VBZ      42308         0.551437              1
15     PRP       7850         0.102316              1
16     JJR       6410         0.083547              1
17      DT      11435         0.149042              1
18      UH        175         0.002281              1
19     WP$       1631         0.021258              1
20     SYM       1292         0.016840              1
21      CC       1866         0.024321              1
22     WDT        748         0.009749              1
23    NNPS         52         0.000678              1
24     WRB         83         0.001082              1
25      FW        188         0.002450              1
26      WP         34         0.000443              1
27     RBS         12         0.000156              1
28    PRP$          3         0.000039              1
0      VBG      75637         4.063711              0
1       NN     951498        51.120654              0
2      NNS     293452        15.766148              0
3       JJ     140953         7.572911              0
4       RB      61921         3.326798              0
5      PRP        658         0.035352              0
6       VB      29016         1.558928              0
7      VBN     118901         6.388134              0
8      JJS       4345         0.233442              0
9       IN      17845         0.958749              0
10      CD      15783         0.847965              0
11     NNP      99024         5.320213              0
12     VBZ       7227         0.388281              0
13     RBR       1628         0.087467              0
14     JJR       1770         0.095096              0
15      DT       3648         0.195994              0
16     VBD      32944         1.769966              0
17      MD       3427         0.184121              0
18      UH        145         0.007790              0
19      CC        151         0.008113              0
20     SYM        371         0.019933              0
21     WP$        315         0.016924              0
22      WP         65         0.003492              0
23     WDT        111         0.005964              0
24      FW        138         0.007414              0
25     WRB         21         0.001128              0
26     RBS          6         0.000322              0
27    NNPS        273         0.014667              0
28    PRP$          6         0.000322              0

In [35]:
#save to csv
df_pos_tag.to_csv('/content/drive/My Drive/My Folder/pos_tag.csv')

In [36]:
df_pos_tag=pd.read_csv('/content/drive/My Drive/My Folder/pos_tag.csv')

In [37]:
df_pos_tag_vis=df_pos_tag[df_pos_tag['frequency_ratio']>=1.3]

In [38]:
for index, r in df_pos_tag_vis.iterrows():
  if r['pos_tag']=='JJ':
    df_pos_tag_vis.at[index, 'pos_tag']='adjective'
  if r['pos_tag']=='NN':
    df_pos_tag_vis.at[index, 'pos_tag']='noun, singular'
  if r['pos_tag']=='NNS':
    df_pos_tag_vis.at[index, 'pos_tag']='noun, plural'
  if r['pos_tag']=='NNP':
    df_pos_tag_vis.at[index, 'pos_tag']='proper noun, singular'
  if r['pos_tag']=='VBN':
    df_pos_tag_vis.at[index, 'pos_tag']='verb, past participler'
  if r['pos_tag']=='VBG':
    df_pos_tag_vis.at[index, 'pos_tag']='verb, gerund'
  if r['pos_tag']=='RB':
    df_pos_tag_vis.at[index, 'pos_tag']='adverb'
  if r['pos_tag']=='VBD':
    df_pos_tag_vis.at[index, 'pos_tag']='verb, past tense'
  if r['pos_tag']=='VB':
    df_pos_tag_vis.at[index, 'pos_tag']='verb'

In [39]:
#Visualisation
fig=px.histogram(df_pos_tag_vis, x='pos_tag', y='frequency_ratio', title='POS Tagging Frequency in Fake and Real News', barmode='group', color='news_category', color_discrete_sequence=px.colors.qualitative.Vivid)
fig.update_xaxes(title='POS Tagging').update_yaxes(title='Frequency')
fig.update_layout(xaxis={'categoryorder':'total descending'}, width=1400, height=500)
fig.show()

Word frequency in fake news

In [4]:
df_word_fre_fake=pd.read_csv('/content/drive/My Drive/My Folder/word_freq_fake.csv')

In [11]:
df_word_fre_fake

       Unnamed: 0      word  frequency  frequency_ratio  news_category
0               0   Posting          4         0.000218              0
1               1   Country         48         0.002621              0
2               2        ZA          1         0.000055              0
3               3      Full         55         0.003003              0
4               4      Time         75         0.004095              0
...           ...       ...        ...              ...            ...
97632       97632   Neguede          1         0.000055              0
97633       97633    julius          1         0.000055              0
97634       97634    malema          1         0.000055              0
97635       97635  Sixolise          1         0.000055              0
97636       97636  Gcilishe          1         0.000055              0

[97637 rows x 5 columns]

In [12]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

In [ ]:
Creating empty WordCloud object and generating actual WordCloud.
wordcloud = WordCloud().generate(input)